# Generated by Django 4.1.3 on 2022-11-04 07:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('236b1b4a-f30c-442e-b6c7-0af5aa445a4e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
